### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by moriel5** [maltaisn/another-notes-app#5]
How should I go about translating `Another Notes App` (should I find the time to do so)?
Just translate `values.xml`and send it in an additional `values`directory corresponding to my language via a pull request?

**Comment by maltaisn** [comment]
> Just translate `values.xml`and send it in an additional `values`directory corresponding to my language via a pull request?

That's pretty much it. You can do it at any time but if you'd prefer to make a single pull request to translate the whole thing I can notify you before making a release.

**Comment by moriel5** [comment]
Thanks, that would be great.
I'll probably make a single pull request, since I usually work on translations from a text editor (though there are exceptions, such as `Stringlate` and `POEditor`, for Android and desktop Linux respectively, since they make my life much easier when translating software strings), so a notification before release would be great (assuming I don't send the pull request earlier, in which case, it would still be great, if there are additional strings added later).

**Comment by maltaisn** [comment]
If you want to translate the app you can do it. I'll be making a release soon, I don't think I'll be adding any more strings until then.

**Comment by moriel5** [comment]
Thanks. To be honest, I just got around to starting a sorry while ago.
I currently have some chores to finish, and then I'll return to translating.

Also, there were a few strings that I wasn't able to understand their context, so I'll ask you about them when I return to translate the app.

**Comment by moriel5** [comment]
I'm almost done translating, however there are three points that either need clarification and/or I am stuck, as well as a few more that probably won't translate well, as things are currently within the app.

1. (Least important, however) Should I leave the name as is, it would you like me to either translate or transliterate it?

2. "Cancel" and "Undo" share the same word in Hebrew, so I am trying to think to put for "Undo" (I'll probably rely on what I used for translating MiXplorer).

3. The "note_placeholder_active" string has a bunch of slashes, as well as "nClick" in the value. What am I supposed to do with those?

4. While I know what strikethrough is, I am currently having a hard time deciding how to translate it, as I can't seem to think, not find, a translation for it as a verb, rather than just a noun.

Additionally, where the number is counted, there could be an issue where if only one item is there, in Hebrew it should be structured thus: "Item one selected", rather than "One item selected". I have had this issue in the past when translating MiXplorer, though I forget what HootanParsa did to take care of that.

**Comment by maltaisn** [comment]
1. You can leave it as is if you think that's best. When I translated in French I decided to leave the name in English because it was a bit long in French. I don't think it matters too much in the end.
2. Both strings never occur together so that's not really an issue.
3. You need to escape single quotes with a slash. The `\n` is a line break escape, you can leave it. If I had used a regular line break the system would have just merged both lines with a space between them.
4. Here's a good resource that might help you: https://www.microsoft.com/en-us/language/Search?&searchTerm=strikethrough&langID=378&Source=true&productid=0. You can also reformulate it so that it's used as a noun e.g: "Mark checked list items with a strikethrough"

Do you have a particular string in mind for your last point? I think the only place where a number of selected items is shown, only the number itself is shown.

I think the [recurrence library](https://github.com/maltaisn/recurpickerlib) used by the app has no Hebrew translation so you'll need to translate it too to have the full interface in one language.

**Comment by moriel5** [comment]
Thanks:

1. In Hebrew, it should be about the same length (perhaps 2-3 characters more), however I'll do the same as you, for consistency.

2. It could still potentially be confusing for users, so I did as with MiXplorer, and translated "Cancel" as a noun, and "Undo" as a first-person verb (i.e. rough equivalent of "you undo", though in Hebrew, the "you" is not a separate word, but rather changes the word itself). 

3. Thanks, will follow that as well.

4. Thanks, this helped me verify that there is no direct equivalent to "strikethrough" as a verb to Hebrew. Formulating the sentence like that is also not coherent than other options I can see, so I'll do that.

Regarding numbers, the particular string is "note_list_item_info".

I understand, though I do not seem to see the other translations alluded to there?

**Comment by maltaisn** [comment]
> Regarding numbers, the particular string is "note_list_item_info".

This string appears when a list note has more items that can be displayed in preview:
<img src="https://user-images.githubusercontent.com/33690959/117075885-8bfc3180-ad03-11eb-8274-5e12143d196d.png" width="500px"/>

I'll let you see what's the most appropriate way to translate it. You can specify separate strings for one/two/few/many/other as needed.


> I understand that I would transfer the library, though I do not seem to see the other translations alluded to there?

It needs to be done separately, the library has its own strings.xml file. The library provides a dialog and a class to show recurrence rules in a localized way, both of which is used by the app.

**Comment by moriel5** [comment]
Yeah, that is precisely what I had meant regarding the order, though I guess Hebrew-speaking users will have to live with it, since I see no way to improve upon that.

Regarding the library, thanks, I was simply looking in the wrong place, I'll get to it soon.

**Comment by maltaisn** [comment]
You can move the `%d` specifier (where the number is inserted) entirely if you want, even omit it.

**Comment by moriel5** [comment]
That is true, however it may look weird to see the number jump right (Hebrew is RTL) when it goes from 1 to 2.

I think it'll be a good idea if I ask friends of mine in our Telegram group for their opinion (though not everyone uses their devices in Hebrew, some (like me) use them in English, some use them in Russian, as well as a few other languages).

**Comment by maltaisn** [comment]
I'll close this since the translation process is described in details in [TRANSLATION.md](https://github.com/maltaisn/another-notes-app/blob/master/TRANSLATING.md). If you find time to finish your translation, you can do it on the Crowdin project, I think it'll be simpler since there are screenshots for every string.

**Comment by moriel5** [comment]
Thanks, these are busy times for me.
Hopefully once I finish replacing/rebuilding/modifying a few living necessities that broke down I be able to get to it.
